# Use postgres/example user/password credentials
version: '3.9'

services:
  flask:
    build: app
    ports: 
      - "5001:5001"
    volumes:
      - ./app:/home
      - ./data:/home/data
    environment:
      FLASK_APP: label
      FLASK_ENV: development
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 5001

  jupyter:
    build: app
    volumes: 
      - ./:/home
    ports: 
      - "5002:8888"
    command: jupyter lab --allow-root --ip 0.0.0.0 --port 8888 --NotebookApp.token='' --NotebookApp.password=''

  db:
    build: postgres
    restart: always
    volumes: 
      - ./data/:/data
    environment:
      POSTGRES_PASSWORD: example

